### ISSUE TITLE
I got this message when google called callback

### ISSUE THREAD

**Issue by napatwongchr** [mstade/passport-google-oauth2#8]
I tried to find the way to fix this and still no clue. I want to know what's going on
please help me
thank you

> Error
>     at C:\Users\Admin-PC\Documents\Ecommerce-Cores\authentication\node_modules\passport-google-oauth2\lib\oauth2.js:92:28
>     at passBackControl (C:\Users\Admin-PC\Documents\Ecommerce-Cores\authentication\node_modules\oauth\lib\oauth2.js:132:9)
>     at IncomingMessage.<anonymous> (C:\Users\Admin-PC\Documents\Ecommerce-Cores\authentication\node_modules\oauth\lib\oauth2.js:157:7)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Soviut** [comment]
@napatwongchr I got the same issue and solved it by switching to the `passport-google-oauth20` package.

**Comment by vincenzorm117** [comment]
Neither worked for me, I'm stilling getting the same error as @napatwongchr

**Comment by mathurs** [comment]
It has probably to do with Google + Api not enabled. Please enable it and then try again.

**Comment by napatwongchr** [comment]
@mathurs yeah, you're right. my mistake.
